name: Unit Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false

    services:
      mongodb:
        image: mongo:5.0.5
        env:
          MONGO_INITDB_DATABASE: greenhouse
          MONGO_INITDB_ROOT_USERNAME: farmer
          MONGO_INITDB_ROOT_PASSWORD: tractor
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install required libs
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
        env:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          ENVIRONMENT: test
          TESTING: 0
          UP: up
          DOWN: down
          WEB_SERVER: web_server
          MONGO_HOST: mongodb
          MONGO_PORT: 27017
          MONGO_USER: farmer
          MONGO_PASS: tractor
          MONGO_DB: greenhouse
          MONGO_COLLECTION: greens
          MONGO_TEST_DB: farmland
          MONGO_URL: mongodb://farmer:tractor@127.0.0.1:27017/?retryWrites=true&w=majority
